services:
   redis: 
     image: redislabs/redismod
     ports:
       - '6379:6379' 
     networks:
       - ecom
   web:
        image: backendmentorship-web
        ports:
            - "8000:80"
        networks:
            - ecom
        depends_on:
            - redis
            - mongo
        volumes:
            - mongodata:/data/db
   mongo:
        image: mongo
        ports:
        -  '27017:27017'
        networks:
        -  ecom

networks:
  ecom:
volumes:
  mongodata:
